name: Build and Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:
    types: [review_requested]
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install ðŸ”§
        run: pnpm install
      - name: Build ðŸ”§
        run: pnpm build
      - name: Format ðŸ‘•
        run: |
          pnpm lint
          pnpm format
      - name: Tests âœ”ï¸
        run: |
          pnpm test:ci
  e2e-tests:
    name: Playwright@${{ matrix.playwright}} ${{ matrix.os }} headless=${{ matrix.headless }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        playwright: [1.8.0, 1.12.0, 1.18.0, next, beta]
        headless: [true, false]
        exclude:
          - os: ubuntu-20.04
            playwright: 1.0.0
          - os: ubuntu-20.04
            playwright: 1.1.0
          - os: ubuntu-20.04
            playwright: 1.2.0
          - os: ubuntu-22.04
            playwright: 1.23
          - os: ubuntu-22.04
            playwright: 1.25
          - os: ubuntu-22.04
            playwright: next
          - os: ubuntu-20.04
            playwright: latest
          - os: macos-latest
            playwright: 1.8.0
          - os: macos-latest
            playwright: 1.12.0
          - os: macos-latest
            playwright: 1.18.0
        include:
          - os: ubuntu-22.04
            playwright: next

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install ðŸ”§
        run: pnpm install
      - name: Install dependencies
        run: pnpmnpm install playwright@${{ matrix.playwright }} && npx playwright install
        # Headless running is the same across OSes
      - name: Run Playwright (headless)
        if: ${{ matrix.headless == true }}
        run: pnpm test:e2e

        # Headful is different in every OS
      - name: Run Playwright (headful linux)
        if: ${{ matrix.headless == false && startsWith(matrix.os, 'ubuntu') }}
        run: HEADFUL=true xvfb-run --auto-servernum -- pnpm test:e2e
      - name: Run Playwright (headful windows)
        if: ${{ matrix.headless == false && startsWith(matrix.os, 'windows') }}
        run: HEADFUL=true pnpm test:2e2e
        shell: bash
      - name: Run Playwright (headful mac)
        if: ${{ matrix.headless == false && startsWith(matrix.os, 'mac') }}
        run: HEADFUL=true pnpm test:e2e
